### ISSUE TITLE
Vex.Extract not implemented for %{}

### ISSUE THREAD

**Issue by churcho** [CargoSense/vex#28]
Is it possible to simply validate a map on the fly without creating a struct with the validation definitions? I would like to validate values coming from my Plug.Con request without having to perform `Vex.Validators.Presence.validate` on each one of those values.

Let's assume I need to check for the existance of all these keys 

`%{"country" => "KE", "email" => "me@test.com", "ip" => "32.217.45.88", "password" => "######", "phone" => "567890432"}`

Right now I am thinking my only option is to recursively run through it, get the keys and check for for those using Precence.validate

**Comment by djspinmonkey** [comment]
Is this still a valid issue? Looking at https://github.com/CargoSense/vex/blob/master/lib/vex/extract.ex#L24 it seems that Vex.Extract is now implemented for maps. That seems to have been added in https://github.com/CargoSense/vex/pull/17, which was about a year and a half after this issue was opened.

**Comment by dkushner** [comment]
I am also having this issue with version 0.5.5.

```elixir
** (Protocol.UndefinedError) protocol Vex.Extract not implemented for %{children: [%{type: "header"}, %{type: "footer"}, %{type: "body"}], options: %{}, type: "root"}
```

**Comment by djspinmonkey** [comment]
Ah, hm, yes, looks like that release was back in January. This issue seems to have been fixed in https://github.com/CargoSense/vex/pull/17, which is slotted for the 0.6 release, which hasn't happened.

@bruce, any reason I shouldn't go ahead and cut a new 6.0 release? Relatedly, how would I go about cutting a new 6.0 release? ;-)

**Comment by dkushner** [comment]
@djspinmonkey, nice response time! Looking forward to the new release.

**Comment by bruce** [comment]
@djspinmonkey Send me the email address you have registered with hex.pm and I'll add you as a project owner; then it's just a version bump in `mix.exs` and a `mix hex.publish` away.

**Comment by djspinmonkey** [comment]
It's john@djspinmonkey.com (same as on my github account, and also on my everything everywhere, so I don't mind just posting it here ;-) ).

**Comment by bruce** [comment]
@djspinmonkey DONE. 🚀

**Comment by djspinmonkey** [comment]
Ok! v0.6.0 is pushed. I'll make some release notes.
